export const SUBSIDY_REQUEST_START = 'SUBSIDY_REQUEST_START';
export const SUBSIDY_REQUEST_SUCCESS = 'SUBSIDY_REQUEST_SUCCESS';

export const FETCH_SUBSIDY_REQUEST_START = 'FETCH_SUBSIDY_REQUEST_START';
export const FETCH_SUBSIDY_REQUEST_SUCCESS = 'FETCH_SUBSIDY_REQUEST_SUCCESS';

export const POST_AD_START = 'POST_AD_START';
export const POST_AD_SUCCESS = 'POST_AD_SUCCESS';

export const FETCH_ADS_START = 'FETCH_ADS_START';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';